[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^6.21.2
    # mbedTLS is bundled with ESP-IDF, so no need to add separately
build_unflags = 
	-std=gnu++11
build_flags = 
	-std=gnu++17
